[profile.default]
src = "src"
out = "out"
libs = ["lib"]

eth-rpc-url="https://testnet-rpc.monad.xyz"
chain_id = 10143

remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "forge-std/=lib/forge-std/src/"
]

optimizer = true
optimizer_runs = 200

default_network = "monad"

[rpc_endpoints]
monad = "https://testnet-rpc.monad.xyz"

